import "./globals.css";
import localFont from 'next/font/local'


const oracle = localFont({
  src: [
    {
      path: '../../public/fonts/ABCOracleCyrillicPlusVariable-Trial.woff2',
      weight: '100 900',
      style: 'normal',
    },
    {
      path: '../../public/fonts/ABCOracleCyrillicPlusVariable-Trial.woff',
      weight: '100 900', 
      style: 'normal',
    }
  ],
  display: 'swap',
  variable: '--font-oracle',
  fallback: ['Arial', 'Helvetica', 'sans-serif'],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={oracle.variable}>
      <body className={oracle.className}>
        {children}
      </body>
    </html>
  );
}
