import "./globals.css";
import localFont from 'next/font/local'


const oracle = localFont({
  src: '../../public/fonts/ABCOracleCyrillicPlusVariable-Trial.woff',
  display: 'swap',
  variable: '--font-oracle',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={oracle.variable}>
      <body

      >
        {children}
      </body>
    </html>
  );
}
